sudo: required
services:
  - docker

before_install:
  - docker build -t aniekannu/docker-react -f Dockerfile.dev .

script:
  - docker run -p 8080:8080 aniekannu/docker-react npm run test -- --coverage
